import {
  Users, Building2, Truck, FileText, Calculator, Calendar,
  HardHat, Wrench, Package, Shield, Ship, DollarSign,
  BookOpen, Leaf, BarChart3
} from 'lucide-react';

export const moduleConfigs = {
  'lead-management': {
    name: 'Lead Management',
    icon: Users,
    description: 'Centralize and score all leads. AI finds high-fit buyers, drafts follow-ups, and logs interactions.',
    ownerImpact: 'More RFQs from same outreach',
    employeeImpact: 'Less manual sorting; AI suggests next touch',
    keyFeatures: [
      'Centralized lead inbox',
      'AI-powered lead scoring',
      'Automated follow-up drafts',
      'Multi-channel campaign builder',
      'Interaction history tracking',
      'Lead quality analytics',
    ],
    aiCapabilities: [
      'High-fit buyer detection',
      'Auto-draft personalized emails',
      'Smart lead prioritization',
      'Next best action suggestions',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Essential lead management',
        features: ['Lead inbox', 'Manual import', 'Basic contact log', 'Email integration'],
      },
      {
        name: 'Growth',
        description: 'AI-powered lead optimization',
        features: ['Everything in Basic', 'Campaign builder', 'AI scoring', 'Auto follow-ups', 'WhatsApp integration'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Complete omni-channel solution',
        features: ['Everything in Growth', 'LinkedIn integration', 'Advanced analytics', 'Custom workflows', 'API access'],
      },
    ],
    onboardingSteps: [
      {
        id: 'upload-leads',
        title: 'Upload Your Lead List',
        description: 'Import existing leads from CSV, Excel, or CRM export to get started instantly',
        instruction: 'Upload a file with columns: Company Name, Contact Name, Email, Phone, Industry, Location, Source, Notes. MARBIM will auto-enrich missing data like company size, website, and LinkedIn profiles. Accepted formats: CSV, XLSX, or direct CRM export from Salesforce/HubSpot.',
        aiHelp: 'What format should my lead list be in? Show me a sample CSV template for Lead Management.',
        expectedOutcome: 'All leads imported, duplicates merged, missing data enriched by AI',
        estimatedTime: '5-10 minutes',
      },
      {
        id: 'connect-email',
        title: 'Connect Email Account',
        description: 'Link your email to enable automated follow-ups, tracking, and seamless communication',
        instruction: 'Connect your Gmail, Outlook, or SMTP server to send and track emails directly from fabricXai. We use OAuth 2.0 secure authentication—your password is never stored. Enable email tracking to see opens, clicks, and replies in real-time. Set up email templates for common scenarios like introductions, follow-ups, and RFQ requests.',
        aiHelp: 'How do I safely connect my email account? What permissions does fabricXai need?',
        expectedOutcome: 'Email connected, test email sent successfully, tracking active',
        estimatedTime: '3-5 minutes',
      },
      {
        id: 'scoring-rules',
        title: 'Define Scoring Rules',
        description: 'Train AI to identify and prioritize your most valuable leads automatically',
        instruction: 'Configure scoring criteria that matter to your business: Annual order volume (weight: 30%), Geographic location preference (20%), Product category match (20%), Company size/revenue (15%), Response history (15%). Set threshold scores: Hot Lead (80+), Warm (60-79), Cold (<60). MARBIM learns from your past conversions to continuously improve accuracy.',
        aiHelp: 'What scoring criteria should I use for garment buyers? Show me industry best practices.',
        expectedOutcome: 'Scoring model configured, leads auto-prioritized, test scores verified',
        estimatedTime: '10-15 minutes',
      },
      {
        id: 'ai-followup',
        title: 'Activate AI Follow-up',
        description: 'Enable MARBIM to draft personalized follow-up messages and automate nurture sequences',
        instruction: 'Set your communication tone (Professional, Friendly, or Custom), define follow-up intervals (3 days, 7 days, 14 days), and configure approval workflow (Auto-send or Require approval). MARBIM will draft contextual messages based on lead behavior—different messages for email opens, website visits, or no engagement. Set quiet hours to avoid sending emails at night.',
        aiHelp: 'How does AI follow-up work without being too pushy? Can I review messages before they send?',
        expectedOutcome: 'AI follow-up active, first campaign scheduled, approval workflow set',
        estimatedTime: '8-12 minutes',
      },
    ],
  },

  'buyer-management': {
    name: 'Buyer Management',
    icon: Building2,
    description: 'Manage all buyers, contracts, and sentiment health in one place.',
    ownerImpact: 'Predict churn early',
    employeeImpact: 'AI drafts replies, organizes buyer data',
    keyFeatures: [
      'Comprehensive buyer directory',
      'Contract management',
      'Sentiment analysis',
      'SLA monitoring',
      'Churn prediction',
      'Buyer portal access',
    ],
    aiCapabilities: [
      'Early churn detection',
      'Automated response drafting',
      'Sentiment tracking',
      'Risk alerts',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Core buyer management',
        features: ['Buyer directory', 'Contact log', 'Basic notes', 'Order history'],
      },
      {
        name: 'Growth',
        description: 'Intelligent buyer insights',
        features: ['Everything in Basic', 'AI churn prediction', 'SLA monitor', 'Sentiment tracking', 'Auto responses'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Full buyer engagement suite',
        features: ['Everything in Growth', 'Buyer portal access', 'Advanced analytics', 'Custom integrations', 'Multi-tier support'],
      },
    ],
    onboardingSteps: [
      {
        id: 'import-buyers',
        title: 'Import Buyer Database',
        description: 'Upload your complete buyer list to centralize all customer relationships',
        instruction: 'Import buyers with: Company name, primary contacts, buyer tier (Strategic/Growth/Standard), location, product categories, payment terms, credit limits, and contract dates. Include historical order data if available. MARBIM will auto-enrich company profiles with public data (revenue, employee count, social media). Supports CSV, Excel, or direct CRM import.',
        aiHelp: 'What buyer information should I import? Show me a complete buyer data template.',
        expectedOutcome: 'All buyers imported, profiles enriched, tier classification complete',
        estimatedTime: '10-15 minutes',
      },
      {
        id: 'upload-contracts',
        title: 'Upload Buyer Contracts & Agreements',
        description: 'Digitize all buyer agreements, MOUs, and commercial terms',
        instruction: 'Upload PDF contracts or manually enter key terms: Pricing agreements, annual volume commitments, payment terms (LC/TT/DA), credit limits, SLA requirements (lead times, quality AQL), penalty clauses, and renewal dates. Link contracts to buyer profiles. MARBIM extracts key dates and sets auto-reminders for renewals and compliance deadlines.',
        aiHelp: 'How should I organize my buyer contracts? What key terms should I track?',
        expectedOutcome: 'Contracts uploaded, key terms extracted, renewal alerts configured',
        estimatedTime: '15-20 minutes',
      },
      {
        id: 'sentiment-tracking',
        title: 'Enable AI Sentiment Tracking',
        description: 'Connect communication channels for real-time buyer satisfaction monitoring',
        instruction: 'Link email (Gmail/Outlook), WhatsApp Business API, and other channels. MARBIM analyzes every buyer interaction—emails, calls, complaints, orders—to calculate sentiment scores (Positive/Neutral/Negative). Configure alert thresholds: Get notified when sentiment drops below 60% or when negative keywords appear ("disappointed", "delay", "quality issue"). Set up weekly sentiment reports for key accounts.',
        aiHelp: 'How does sentiment tracking work? What triggers negative sentiment alerts?',
        expectedOutcome: 'Channels connected, sentiment baseline established, alerts active',
        estimatedTime: '8-12 minutes',
      },
      {
        id: 'launch-dashboard',
        title: 'Launch Buyer 360 Dashboard',
        description: 'Activate comprehensive buyer intelligence and health monitoring',
        instruction: 'Review your Buyer 360 dashboard showing: Health scores (order frequency, payment behavior, communication), churn risk predictions, tier distribution, regional revenue breakdown, and top accounts. Verify buyer data accuracy, configure custom fields (brands, seasons, product lines), set up role-based access for sales team, and activate automated health reports. Configure "Silent Buyer" alerts (no orders in 60 days) and payment overdue notifications.',
        aiHelp: 'Show me how to use the Buyer 360 dashboard effectively. What alerts should I set?',
        expectedOutcome: 'Dashboard live, team access configured, automated alerts active',
        estimatedTime: '10-15 minutes',
      },
    ],
  },

  'supplier-evaluation': {
    name: 'Supplier Evaluation',
    icon: Truck,
    description: 'Compare supplier quotes, certifications, and reliability.',
    ownerImpact: 'Better sourcing decisions',
    employeeImpact: 'Auto-shortlisting and scorecards',
    keyFeatures: [
      'Supplier directory',
      'RFQ comparison',
      'Certification tracking',
      'Performance scorecards',
      'Audit management',
      'Supplier portal',
    ],
    aiCapabilities: [
      'AI-based supplier ranking',
      'Auto quote normalization',
      'Risk assessment',
      'Smart recommendations',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Manual supplier management',
        features: ['Supplier directory', 'Manual RFQ comparison', 'Basic scorecards', 'Document storage'],
      },
      {
        name: 'Growth',
        description: 'AI-powered sourcing',
        features: ['Everything in Basic', 'AI-based ranking', 'Auto shortlisting', 'Performance analytics', 'Audit tracker'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Complete supply chain intelligence',
        features: ['Everything in Growth', 'Supplier portal', 'Audit sync', 'API integration', 'Multi-country compliance'],
      },
    ],
    onboardingSteps: [
      {
        id: 'upload-suppliers',
        title: 'Upload Supplier Database',
        description: 'Import your complete supplier network for centralized management',
        instruction: 'Add suppliers with: Company name, contact details, product categories (fabric/trims/accessories), location, certifications (OEKO-TEX, GOTS, ISO), payment terms, lead times, and minimum order quantities. Include performance history if available. MARBIM will enrich profiles with compliance data, financial stability scores, and market reputation. Supports CSV, Excel, or direct ERP import.',
        aiHelp: 'What supplier information should I track? Show me a supplier data template.',
        expectedOutcome: 'All suppliers imported, profiles enriched, categories organized',
        estimatedTime: '12-18 minutes',
      },
      {
        id: 'import-audits',
        title: 'Import Audit Reports & Certifications',
        description: 'Digitize all supplier audits, certifications, and compliance documents',
        instruction: 'Upload audit PDFs (social, environmental, technical), certification documents (WRAP, BSCI, SEDEX, SA8000), factory inspection reports, and compliance records. MARBIM extracts key findings, non-conformances, CAPA status, and expiry dates. Set auto-reminders for certificate renewals (30/60/90 days before expiry). Organize by supplier and compliance standard. Link to supplier profiles for quick access.',
        aiHelp: 'How do I organize supplier audit data? What certifications are critical for garment sourcing?',
        expectedOutcome: 'Audits uploaded, findings extracted, renewal reminders active',
        estimatedTime: '20-25 minutes',
      },
      {
        id: 'ai-normalize',
        title: 'AI Quote Normalization & Comparison',
        description: 'Let AI standardize quotations from different suppliers for apples-to-apples comparison',
        instruction: 'Upload 5-10 sample quotes in any format (PDF, email, Excel, handwritten scans). MARBIM extracts pricing, MOQs, lead times, payment terms, and quality specs—even from unstructured formats. AI normalizes different units (meters/yards, kg/lbs), currencies (auto-converts using live FX rates), and terms (FOB/CIF/EXW). Creates side-by-side comparison tables with total landed cost calculations. Train AI on your preferred quote format.',
        aiHelp: 'How does AI compare quotes from different suppliers? Can it handle multiple currencies and units?',
        expectedOutcome: 'Quotes normalized, comparison engine trained, test comparison successful',
        estimatedTime: '15-20 minutes',
      },
      {
        id: 'scorecard-live',
        title: 'Activate Supplier Performance Scorecards',
        description: 'Launch real-time supplier performance tracking with AI-powered insights',
        instruction: 'Configure scorecard criteria and weights: Quality performance (30% - defect rates, rejections, CAPA completion), Delivery performance (25% - on-time delivery, lead time accuracy), Pricing competitiveness (20% - cost trends, payment terms), Compliance (15% - audit scores, certifications), Communication (10% - responsiveness, issue resolution). Set performance thresholds: Excellent (90+), Good (75-89), Needs Improvement (60-74), Critical (<60). MARBIM calculates real-time scores based on actual performance data.',
        aiHelp: 'What should I include in supplier scorecards? How do I weight different performance factors?',
        expectedOutcome: 'Scorecards configured, performance tracking live, alerts for underperforming suppliers',
        estimatedTime: '12-15 minutes',
      },
    ],
  },

  'rfq-quotation': {
    name: 'RFQ & Quotation',
    icon: FileText,
    description: 'Parse RFQs, auto-fill BOM, generate quotes.',
    ownerImpact: 'Faster response → higher win rate',
    employeeImpact: 'No retyping specs',
    keyFeatures: [
      'RFQ parsing',
      'Auto BOM generation',
      'Quote templates',
      'Multi-style quoting',
      'Version control',
      'Buyer sync',
    ],
    aiCapabilities: [
      'Intelligent RFQ parsing',
      'Auto-fill specifications',
      'Price optimization',
      'Multi-language support',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Essential quoting tools',
        features: ['RFQ upload', 'AI parsing', 'Basic quote templates', 'PDF export'],
      },
      {
        name: 'Growth',
        description: 'Smart quotation engine',
        features: ['Everything in Basic', 'BOM auto-fill', 'Advanced templates', 'Version tracking', 'Email integration'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Enterprise quoting platform',
        features: ['Everything in Growth', 'Multi-language quotes', 'Buyer portal sync', 'API access', 'Custom workflows'],
      },
    ],
    onboardingSteps: [
      {
        id: 'upload-rfqs',
        title: 'Upload Sample RFQs',
        description: 'Import historical RFQs for AI training',
        instruction: 'Upload 5-10 past RFQs in any format (PDF, email, Excel)',
        aiHelp: 'What RFQ formats does the AI understand?',
      },
      {
        id: 'connect-buyer',
        title: 'Connect Buyer Module',
        description: 'Link with buyer database',
        instruction: 'Connect to auto-populate buyer details in quotes',
        aiHelp: 'How does buyer integration help with quoting?',
      },
      {
        id: 'train-templates',
        title: 'Train AI on Templates',
        description: 'Upload your quote templates',
        instruction: 'Add your standard quote formats - AI will learn your style',
        aiHelp: 'How do I create effective quote templates?',
      },
      {
        id: 'test-parse',
        title: 'Test RFQ Parsing',
        description: 'Try parsing a real RFQ',
        instruction: 'Upload a new RFQ and see AI extract all details automatically',
        aiHelp: 'What if AI misses some details?',
      },
    ],
  },

  'costing': {
    name: 'Costing',
    icon: Calculator,
    description: 'AI-driven cost sheet builder with yield prediction.',
    ownerImpact: 'Accurate margins',
    employeeImpact: 'Auto-updated rates and FX',
    keyFeatures: [
      'Cost sheet builder',
      'BOM costing',
      'Yield prediction',
      'Multi-currency',
      'Scenario modeling',
      'Margin analysis',
    ],
    aiCapabilities: [
      'AI margin optimization',
      'Price band recommendations',
      'Cost trend analysis',
      'Risk alerts',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Manual cost sheets',
        features: ['Cost sheet builder', 'Manual input', 'Basic BOM', 'PDF export'],
      },
      {
        name: 'Growth',
        description: 'Intelligent costing',
        features: ['Everything in Basic', 'AI optimize', 'Auto FX update', 'Yield prediction', 'Scenario modeling'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Advanced cost intelligence',
        features: ['Everything in Growth', 'Multi-style batch', 'Custom formulas', 'ERP integration', 'Advanced analytics'],
      },
    ],
    onboardingSteps: [
      {
        id: 'upload-costsheets',
        title: 'Upload Historic Cost Sheets',
        description: 'Import past cost sheets for AI learning',
        instruction: 'Add 10-20 historical cost sheets with actual vs estimated costs',
        aiHelp: 'What cost data helps AI learn best?',
      },
      {
        id: 'overhead-data',
        title: 'Add Overhead Data',
        description: 'Input fixed and variable costs',
        instruction: 'Enter: Electricity, rent, salaries, depreciation, admin costs',
        aiHelp: 'How should I allocate overhead costs?',
      },
      {
        id: 'fx-api',
        title: 'Enable FX API',
        description: 'Connect to live currency rates',
        instruction: 'Integrate with exchange rate API for auto-updates',
        aiHelp: 'Which currencies do I need to track?',
      },
      {
        id: 'price-bands',
        title: 'AI Recommends Price Bands',
        description: 'Get intelligent pricing suggestions',
        instruction: 'Review AI-suggested price ranges based on market and costs',
        aiHelp: 'How does AI determine competitive pricing?',
      },
    ],
  },

  'production-planning': {
    name: 'Production Planning & WIP',
    icon: Calendar,
    description: 'Predict delays, optimize line allocations.',
    ownerImpact: 'Reduce late orders',
    employeeImpact: 'Automated Gantt chart and alerts',
    keyFeatures: [
      'Production scheduling',
      'Line allocation',
      'WIP tracking',
      'Delay prediction',
      'Capacity planning',
      'Gantt charts',
    ],
    aiCapabilities: [
      'AI scheduling optimization',
      'Delay prediction',
      'Bottleneck detection',
      'Auto-reallocation',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Manual planning',
        features: ['Basic scheduling', 'Manual allocation', 'Simple Gantt', 'Order tracking'],
      },
      {
        name: 'Growth',
        description: 'Smart scheduling',
        features: ['Everything in Basic', 'AI scheduling', 'Auto alerts', 'Capacity optimization', 'WIP dashboard'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Intelligent production',
        features: ['Everything in Growth', 'IoT integration', 'Real-time tracking', 'Multi-factory', 'Advanced analytics'],
      },
    ],
    onboardingSteps: [
      {
        id: 'line-capacity',
        title: 'Upload Line Capacity',
        description: 'Define production line capabilities',
        instruction: 'Enter: Line numbers, operators per line, hourly capacity, product types',
        aiHelp: 'How do I calculate line capacity accurately?',
      },
      {
        id: 'import-orders',
        title: 'Import Orders',
        description: 'Upload current order book',
        instruction: 'Add orders with: Style, quantity, delivery date, buyer, complexity',
        aiHelp: 'What order details does AI need for scheduling?',
      },
      {
        id: 'connect-inventory',
        title: 'Connect Inventory',
        description: 'Link with materials availability',
        instruction: 'Integrate to check fabric and trim stock before scheduling',
        aiHelp: 'How does inventory affect production planning?',
      },
      {
        id: 'review-plan',
        title: 'Review AI Plan',
        description: 'Check optimized production schedule',
        instruction: 'Review AI-generated schedule and make adjustments if needed',
        aiHelp: 'How do I read the AI production plan?',
      },
    ],
  },

  'workforce-management': {
    name: 'Workforce Management',
    icon: HardHat,
    description: 'Track attendance, skills, and training.',
    ownerImpact: 'Higher efficiency per shift',
    employeeImpact: 'Auto shift assignment',
    keyFeatures: [
      'Attendance tracking',
      'Skill matrix',
      'Training management',
      'Shift planning',
      'Performance tracking',
      'Payroll integration',
    ],
    aiCapabilities: [
      'Smart shift assignment',
      'Skill gap analysis',
      'Attendance prediction',
      'Performance insights',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Basic workforce tracking',
        features: ['Attendance log', 'Manual shifts', 'Employee directory', 'Basic reports'],
      },
      {
        name: 'Growth',
        description: 'Intelligent workforce',
        features: ['Everything in Basic', 'Skill matrix', 'Training tracker', 'Auto assignments', 'Performance analytics'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Complete HR solution',
        features: ['Everything in Growth', 'IoT biometric sync', 'AI forecasting', 'Payroll integration', 'Advanced analytics'],
      },
    ],
    onboardingSteps: [
      {
        id: 'upload-workers',
        title: 'Upload Worker List',
        description: 'Import employee database',
        instruction: 'Add workers with: Name, ID, role, skills, shift preference, salary grade',
        aiHelp: 'What employee data should I track?',
      },
      {
        id: 'connect-biometrics',
        title: 'Connect Biometrics',
        description: 'Link attendance devices',
        instruction: 'Integrate fingerprint or card readers for automatic attendance',
        aiHelp: 'Which biometric systems are supported?',
      },
      {
        id: 'map-skills',
        title: 'Map Skills',
        description: 'Create skill matrix',
        instruction: 'Define skills needed and rate each worker: Sewing, QC, machine operation, etc.',
        aiHelp: 'How do I build an effective skill matrix?',
      },
      {
        id: 'launch-dashboard',
        title: 'Launch Dashboard',
        description: 'Activate workforce analytics',
        instruction: 'Review dashboard and set up alerts for absences and skill gaps',
        aiHelp: 'Show me key workforce metrics to track',
      },
    ],
  },

  'machine-maintenance': {
    name: 'Machine Maintenance',
    icon: Wrench,
    description: 'Predict breakdowns, automate service scheduling.',
    ownerImpact: 'Minimize downtime',
    employeeImpact: 'Automated service logs',
    keyFeatures: [
      'Machine directory',
      'Preventive maintenance',
      'Breakdown tracking',
      'Service scheduling',
      'Spare parts inventory',
      'IoT integration',
    ],
    aiCapabilities: [
      'Predictive maintenance',
      'Breakdown prediction',
      'Auto scheduling',
      'Performance monitoring',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Manual maintenance',
        features: ['Machine list', 'Manual schedule', 'Service log', 'Basic reports'],
      },
      {
        name: 'Growth',
        description: 'Smart maintenance',
        features: ['Everything in Basic', 'AI predictive maintenance', 'Auto scheduling', 'Spare parts tracking', 'Alerts'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Intelligent asset management',
        features: ['Everything in Growth', 'IoT sensors', 'Vendor API', 'Real-time monitoring', 'Advanced analytics'],
      },
    ],
    onboardingSteps: [
      {
        id: 'upload-machines',
        title: 'Upload Machine List',
        description: 'Import equipment inventory',
        instruction: 'Add machines with: Type, brand, model, serial number, purchase date, location',
        aiHelp: 'What machine details should I track?',
      },
      {
        id: 'define-intervals',
        title: 'Define Maintenance Intervals',
        description: 'Set service schedules',
        instruction: 'Enter recommended maintenance frequency for each machine type',
        aiHelp: 'What are standard maintenance intervals for garment machines?',
      },
      {
        id: 'ai-plan',
        title: 'AI Sets Maintenance Plan',
        description: 'Generate optimized schedule',
        instruction: 'Review AI-generated maintenance calendar and adjust if needed',
        aiHelp: 'How does AI optimize maintenance scheduling?',
      },
      {
        id: 'go-live',
        title: 'Go Live',
        description: 'Activate maintenance tracking',
        instruction: 'Enable alerts and start logging maintenance activities',
        aiHelp: 'Show me how to use the maintenance dashboard',
      },
    ],
  },

  'inventory-management': {
    name: 'Inventory Management',
    icon: Package,
    description: 'Track fabric, trims, and FG stock in real time.',
    ownerImpact: 'Prevent shortages',
    employeeImpact: 'AI reorder reminders',
    keyFeatures: [
      'Stock tracking',
      'Multi-warehouse',
      'Reorder management',
      'Bin allocation',
      'Stock movements',
      'Supplier integration',
    ],
    aiCapabilities: [
      'AI demand forecasting',
      'Smart reorder points',
      'Stock optimization',
      'Shortage prediction',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Manual inventory',
        features: ['Stock ledger', 'Manual tracking', 'Basic reports', 'Simple movements'],
      },
      {
        name: 'Growth',
        description: 'Smart inventory',
        features: ['Everything in Basic', 'AI forecasting', 'Auto reorder alerts', 'Multi-warehouse', 'Supplier sync'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Intelligent supply chain',
        features: ['Everything in Growth', 'IoT bins', 'Real-time tracking', 'Supplier portal', 'Advanced analytics'],
      },
    ],
    onboardingSteps: [
      {
        id: 'stock-ledger',
        title: 'Upload Stock Ledger',
        description: 'Import current inventory',
        instruction: 'Add items with: Material code, description, quantity, unit, location, value',
        aiHelp: 'How should I organize my stock data?',
      },
      {
        id: 'map-warehouses',
        title: 'Map Warehouses',
        description: 'Define storage locations',
        instruction: 'Add warehouses, racks, bins and their capacities',
        aiHelp: 'What is the best way to organize warehouse locations?',
      },
      {
        id: 'connect-suppliers',
        title: 'Connect Suppliers',
        description: 'Link supplier database',
        instruction: 'Integrate suppliers to enable auto-reorder and lead time tracking',
        aiHelp: 'How does supplier integration help inventory?',
      },
      {
        id: 'reorder-alerts',
        title: 'Enable Reorder Alerts',
        description: 'Set up AI-driven reminders',
        instruction: 'Configure reorder points and let AI suggest optimal timing',
        aiHelp: 'How do I set smart reorder points?',
      },
    ],
  },

  'quality-control': {
    name: 'Quality Control',
    icon: Shield,
    description: 'Digitize inline and final inspections.',
    ownerImpact: 'Reduced rework',
    employeeImpact: 'AI defect detection and CAPA',
    keyFeatures: [
      'Inspection checklists',
      'Defect tracking',
      'AQL compliance',
      'CAPA management',
      'Image-based QC',
      'Buyer standards',
    ],
    aiCapabilities: [
      'AI defect detection',
      'Pattern recognition',
      'Root cause analysis',
      'Quality prediction',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Manual QC',
        features: ['Digital checklists', 'Defect log', 'Basic reports', 'Photo capture'],
      },
      {
        name: 'Growth',
        description: 'Smart quality',
        features: ['Everything in Basic', 'AI defect analytics', 'CAPA tracker', 'Trend analysis', 'Buyer AQL sync'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Vision-powered QC',
        features: ['Everything in Growth', 'Vision system integration', 'Real-time detection', 'Advanced AI', 'Multi-line tracking'],
      },
    ],
    onboardingSteps: [
      {
        id: 'buyer-aql',
        title: 'Upload Buyer AQL',
        description: 'Import quality standards',
        instruction: 'Add buyer-specific AQL levels and measurement specs',
        aiHelp: 'What are standard AQL levels for garments?',
      },
      {
        id: 'connect-cameras',
        title: 'Connect Cameras',
        description: 'Integrate vision systems (optional)',
        instruction: 'Link cameras for AI-powered defect detection',
        aiHelp: 'How does vision-based QC work?',
      },
      {
        id: 'learn-defects',
        title: 'AI Learns Defect Patterns',
        description: 'Train AI on your defects',
        instruction: 'Upload past defect images - AI will learn to detect similar issues',
        aiHelp: 'What defect images should I use for training?',
      },
      {
        id: 'go-live',
        title: 'Go Live',
        description: 'Start digital inspections',
        instruction: 'Begin using tablets for inline and final inspections',
        aiHelp: 'Show me how inspectors use the QC app',
      },
    ],
  },

  'shipment': {
    name: 'Shipment & Delivery',
    icon: Ship,
    description: 'Automate bookings, documents, and buyer updates.',
    ownerImpact: 'Higher OTIF',
    employeeImpact: 'Auto buyer alerts and ETA tracking',
    keyFeatures: [
      'Booking management',
      'Document vault',
      'Live tracking',
      'Buyer updates',
      'Carrier integration',
      'Exception alerts',
    ],
    aiCapabilities: [
      'Smart carrier selection',
      'Delay prediction',
      'Auto documentation',
      'Proactive alerts',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Manual logistics',
        features: ['Booking log', 'Document storage', 'Manual tracking', 'Basic reports'],
      },
      {
        name: 'Growth',
        description: 'Smart logistics',
        features: ['Everything in Basic', 'Auto alerts', 'Buyer notifications', 'ETA tracking', 'Exception handling'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Integrated supply chain',
        features: ['Everything in Growth', 'Carrier API', 'Live GPS', 'Custom integrations', 'Advanced analytics'],
      },
    ],
    onboardingSteps: [
      {
        id: 'connect-forwarder',
        title: 'Connect Forwarder',
        description: 'Link freight partners',
        instruction: 'Add forwarder details and API credentials if available',
        aiHelp: 'How do I integrate with freight forwarders?',
      },
      {
        id: 'upload-lanes',
        title: 'Upload Shipping Lanes',
        description: 'Define common routes',
        instruction: 'Add: Origin, destination, transit time, carrier preferences',
        aiHelp: 'What lane information should I track?',
      },
      {
        id: 'live-tracking',
        title: 'Enable Live Tracking',
        description: 'Activate shipment monitoring',
        instruction: 'Connect tracking APIs for real-time updates',
        aiHelp: 'Which tracking systems are supported?',
      },
      {
        id: 'test-alert',
        title: 'Test Alert System',
        description: 'Verify notifications',
        instruction: 'Send test alerts to buyers and internal team',
        aiHelp: 'What shipment alerts should I configure?',
      },
    ],
  },

  'finance': {
    name: 'Finance',
    icon: DollarSign,
    description: 'Control AR/AP, margins, and cash flow with predictive analytics.',
    ownerImpact: 'Margin control',
    employeeImpact: 'AI invoice reconciliation',
    keyFeatures: [
      'AR/AP tracking',
      'Invoice management',
      'Payment tracking',
      'Cash flow forecast',
      'P&L by order',
      'Bank reconciliation',
    ],
    aiCapabilities: [
      'Cash flow prediction',
      'Payment default alerts',
      'Auto reconciliation',
      'Margin optimization',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Basic accounting',
        features: ['Invoice log', 'Payment tracking', 'Basic reports', 'Manual entries'],
      },
      {
        name: 'Growth',
        description: 'Smart finance',
        features: ['Everything in Basic', 'AI cashflow', 'Auto reconciliation', 'Order P&L', 'Alerts'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Integrated finance',
        features: ['Everything in Growth', 'Bank API sync', 'ERP integration', 'Multi-currency', 'Advanced analytics'],
      },
    ],
    onboardingSteps: [
      {
        id: 'import-ledgers',
        title: 'Import Ledgers',
        description: 'Upload financial data',
        instruction: 'Import AR/AP ledgers with: Invoice number, amount, due date, status',
        aiHelp: 'What financial data format is required?',
      },
      {
        id: 'set-terms',
        title: 'Set Payment Terms',
        description: 'Configure buyer/supplier terms',
        instruction: 'Add standard payment terms: 30/60/90 days, LC, advance, etc.',
        aiHelp: 'How should I structure payment terms?',
      },
      {
        id: 'connect-bank',
        title: 'Connect Bank (Optional)',
        description: 'Link bank accounts',
        instruction: 'Integrate banking API for auto-reconciliation',
        aiHelp: 'Is bank integration secure?',
      },
      {
        id: 'launch-dashboard',
        title: 'Launch Finance Dashboard',
        description: 'Activate financial tracking',
        instruction: 'Review dashboard and set up cash flow alerts',
        aiHelp: 'Show me key financial metrics to monitor',
      },
    ],
  },

  'compliance-policy': {
    name: 'Compliance & Policy',
    icon: BookOpen,
    description: 'Manage policies, audits, and NCs.',
    ownerImpact: 'Zero audit failure',
    employeeImpact: 'Automated CAPA tasks',
    keyFeatures: [
      'Policy library',
      'Audit management',
      'NC tracking',
      'CAPA workflow',
      'Certificate management',
      'Regulatory monitoring',
    ],
    aiCapabilities: [
      'Auto CAPA suggestions',
      'Compliance risk alerts',
      'Document summarization',
      'Audit preparation',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Policy repository',
        features: ['Policy library', 'Document storage', 'Basic checklists', 'Manual tracking'],
      },
      {
        name: 'Growth',
        description: 'Smart compliance',
        features: ['Everything in Basic', 'Audit tracker', 'NC management', 'CAPA workflow', 'Alerts'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Integrated compliance',
        features: ['Everything in Growth', 'Supplier compliance sync', 'Multi-standard tracking', 'API access', 'Advanced reports'],
      },
    ],
    onboardingSteps: [
      {
        id: 'upload-policies',
        title: 'Upload Existing Policies',
        description: 'Import policy documents',
        instruction: 'Add: Safety policies, quality policies, HR policies, buyer codes',
        aiHelp: 'What policies should a garment factory have?',
      },
      {
        id: 'connect-audits',
        title: 'Connect Audit Logs',
        description: 'Import past audit reports',
        instruction: 'Upload audit PDFs and findings from past years',
        aiHelp: 'How do I organize audit documentation?',
      },
      {
        id: 'train-ai',
        title: 'Train AI on Standards',
        description: 'Let AI learn compliance requirements',
        instruction: 'Upload compliance standards (WRAP, BSCI, SEDEX, buyer-specific)',
        aiHelp: 'What compliance standards apply to my factory?',
      },
      {
        id: 'go-live',
        title: 'Go Live',
        description: 'Activate compliance tracking',
        instruction: 'Set up audit schedule and NC alert thresholds',
        aiHelp: 'Show me how to prepare for audits',
      },
    ],
  },

  'sustainability': {
    name: 'Sustainability',
    icon: Leaf,
    description: 'Track ESG metrics and DPP traceability.',
    ownerImpact: 'ESG compliance',
    employeeImpact: 'Auto ESG reporting',
    keyFeatures: [
      'Carbon tracking',
      'Water usage',
      'Waste management',
      'Social metrics',
      'Digital Product Passport',
      'ESG reporting',
    ],
    aiCapabilities: [
      'Carbon footprint calculation',
      'Sustainability scoring',
      'Improvement suggestions',
      'Regulatory compliance',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Manual ESG tracking',
        features: ['ESG data input', 'Basic metrics', 'Simple reports', 'Document storage'],
      },
      {
        name: 'Growth',
        description: 'Smart sustainability',
        features: ['Everything in Basic', 'AI footprint calc', 'Waste tracking', 'Social compliance', 'Dashboards'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Digital Product Passport',
        features: ['Everything in Growth', 'GS1 integration', 'QR labels', 'Blockchain traceability', 'Advanced analytics'],
      },
    ],
    onboardingSteps: [
      {
        id: 'upload-metrics',
        title: 'Upload ESG Metrics',
        description: 'Import sustainability data',
        instruction: 'Add: Energy usage, water consumption, waste data, social metrics',
        aiHelp: 'What ESG data should garment factories track?',
      },
      {
        id: 'connect-iot',
        title: 'Connect IoT (Optional)',
        description: 'Link energy/water meters',
        instruction: 'Integrate meters for automatic data collection',
        aiHelp: 'Which IoT sensors work with fabricXai?',
      },
      {
        id: 'baseline-report',
        title: 'Generate Baseline Report',
        description: 'Create ESG baseline',
        instruction: 'AI generates current sustainability score and improvement areas',
        aiHelp: 'How do I interpret my ESG baseline?',
      },
      {
        id: 'go-live',
        title: 'Go Live',
        description: 'Start sustainability tracking',
        instruction: 'Set targets and enable progress monitoring',
        aiHelp: 'What are realistic ESG improvement targets?',
      },
    ],
  },

  'analytics': {
    name: 'Analytics & Reporting',
    icon: BarChart3,
    description: 'Unified KPI dashboard and AI explainers.',
    ownerImpact: 'Full visibility',
    employeeImpact: 'Simplified reporting',
    keyFeatures: [
      'Unified dashboard',
      'Role-based views',
      'Custom reports',
      'AI insights',
      'Scheduled reports',
      'Export capabilities',
    ],
    aiCapabilities: [
      'AI-powered insights',
      'Trend prediction',
      'Anomaly detection',
      'Natural language queries',
    ],
    pricingTiers: [
      {
        name: 'Basic',
        description: 'Standard reports',
        features: ['Pre-built reports', 'Manual generation', 'PDF export', 'Basic filters'],
      },
      {
        name: 'Growth',
        description: 'Smart analytics',
        features: ['Everything in Basic', 'AI explainers', 'Custom dashboards', 'Scheduled reports', 'Trend analysis'],
        recommended: true,
      },
      {
        name: 'Enterprise',
        description: 'Business intelligence',
        features: ['Everything in Growth', 'Custom BI sync', 'API access', 'White-label reports', 'Advanced modeling'],
      },
    ],
    onboardingSteps: [
      {
        id: 'connect-modules',
        title: 'Connect All Modules',
        description: 'Link data sources',
        instruction: 'Ensure all active modules are connected for unified reporting',
        aiHelp: 'Which modules should I activate first?',
      },
      {
        id: 'choose-kpis',
        title: 'Choose Your KPIs',
        description: 'Select key metrics',
        instruction: 'Pick 10-15 most important KPIs for your factory',
        aiHelp: 'What are the most important KPIs for garment factories?',
      },
      {
        id: 'schedule-reports',
        title: 'Schedule Reports',
        description: 'Set up automated reporting',
        instruction: 'Configure daily/weekly/monthly reports and recipients',
        aiHelp: 'What reporting frequency is best?',
      },
      {
        id: 'first-boardpack',
        title: 'Generate First Board Pack',
        description: 'Create executive summary',
        instruction: 'AI generates your first comprehensive management report',
        aiHelp: 'What should a board pack include?',
      },
    ],
  },
};